# Define variables
# NOTE: executable should be a full path
LOGS_DIR=/home/slaing/muon_research/lipschitz_constants/logs
executable=/home/slaing/muon_research/lipschitz_constants/cluster/run.sh

# Job specific vars
config=/home/slaing/muon_research/lipschitz_constants/config/config_regression.yaml
n_jobs=28

# Args
arguments = $(config) $(Process)

# Logs
error = $(LOGS_DIR)/err/regression.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/regression.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/regression.$(Cluster).$(Process).log

# Specs
request_memory = 220000
request_cpus = 12
request_gpus = 1
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")

queue $(n_jobs)
