
# Define variables
LOGS_DIR=/home/slaing/muon_research/lipschitz_constants/logs
executable=/home/slaing/muon_research/lipschitz_constants/cluster/run.sh

# Job specific vars - MUON SWEEP
config=/home/slaing/muon_research/lipschitz_constants/config/sweep_muon.yaml
n_jobs=32

# Args
arguments = $(config) $(Process)

# Logs
error = $(LOGS_DIR)/err/muon_sweep.$(Cluster).$(Process).err
output = $(LOGS_DIR)/out/muon_sweep.$(Cluster).$(Process).out
log = $(LOGS_DIR)/log/muon_sweep.$(Cluster).$(Process).log

# Specs
request_memory = 220000
request_cpus = 12
request_gpus = 1
requirements = (TARGET.CUDADeviceName == "NVIDIA A100-SXM4-80GB")

queue $(n_jobs)
