dataset: "cifar10_5k"
seed: 14
num_workers: 4

iters: 50

model: "mlp"
#hidden dim as proportion of input dim
hidden_dim: 2.5
seperate_biases: false #playing with consuming bias into weights with [W|b][x|1]... maybe eliminates need for 2 optimizers
batch_size: "full"
#optimizer cfg
optimizer: ["muon"]   #, "sgd", "sign_sgd"]
momentum: 0.0
nesterov: false
orthogonalize: true
ns_steps: 5
lr: [0.05, 0.1, 0.2]
beta1: 0.0
beta2: 0.0
eps: 1.e-8
weight_decay: 0.1
adjust_lr: false
precon_nuclear: [false, true]
scheduler: null

track_lipschitz: false
wandb_project_name: "muon_tml"