dataset: "cifar10_5k"
seed: 84 #83 #81  #5
num_workers: 1

iters: 1000

model: "mlp_ortho"
loss: ["cross_entropy"]  # options: "cross_entropy", "mse"
#hidden dim as proportion of input dim
hidden_dim: 1.5
# playing with consuming bias into weights with [W|b][x|1]... maybe eliminates need for 2 optimizers
seperate_biases: true
use_bias: true
activation: "relu"
weight_init: "normal" #["normal", "full_orthogonal"]
batch_size: "full"
#optimizer cfg
optimizer: ["sign_sgd"]   #, "sgd", "sign_sgd"]
momentum: 0.0
nesterov: false
orthogonalize: true
ns_steps: 5
lr:  [1.e-6, 3.e-6, 1.e-5, 3.e-5, 1.e-4, 2.e-4] 
beta1: 0.0
beta2: 0.0
eps: 1.e-8
weight_decay: [0.0]
adjust_lr: false
dual_decay: [false]
scheduler: null

track_hessian: false
hessian_freq: 1 
hessian_k: 5


track_lipschitz: false
wandb_project_name: "orhog_initialization"