dataset: "cifar10_5k"
seed: 20
num_workers: 4

iters: 100

model: "linear_regression"
loss: "mse"  # linear regression uses MSE
hidden_dim: null  # not used for linear regression
seperate_biases: false  # not applicable, we use nn.Linear with bias=True
activation: "linear"  # not used for linear regression
weight_init: ["normal", "full_orthogonal"]
batch_size: "full"
#optimizer cfg
optimizer: ["muon"]   #, "sgd", "sign_sgd"]
momentum: 0.0
nesterov: false
orthogonalize: true
ns_steps: 5
lr: [0.00001, 0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01]
beta1: 0.0
beta2: 0.0
eps: 1.e-8
weight_decay: [0.0]
adjust_lr: false
dual_decay: [false, true]
scheduler: null

track_hessian: false
hessian_freq: 1 
hessian_k: 5

track_lipschitz: false
wandb_project_name: "linear_regression_ortho"
